---
title: Test Jekyll
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
gems:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
permalink: pretty
