---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
- type: field_group_list
  name: sections
  label: Sections
  description: This is a jenky set of images with a column width
  fields:
  - type: file
    name: image
    label: Image
  - type: number
    name: width
    label: Width
    description: Image width (px)
    config:
      min: '0'
      step: '1'
  - type: number
    name: height
    label: Height
    description: Image height (px)
    config:
      min: '0'
      step: '1'
  - type: number
    label: Columns
    name: columns
    description: column width to show this in
    config:
      min: '0'
      step: '1'
      max: '12'
